name: flutter_cdg_karaoke_player
description: Flutter CDG Karaoke Player

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  just_audio: ^0.9.27
  logger: ^1.1.0
  dio: ^4.0.4
  dio_http2_adapter: ^2.0.0
  pretty_dio_logger: ^1.1.1
  audio_session: ^0.1.9
  just_audio_windows: ^0.1.0
  archive: ^3.3.0
  image: ^3.2.0
  bitmap: ^0.1.2
  fluent_ui: ^3.12.0
  provider: ^6.0.3
#  window_manager: ^0.2.5
  desktop_multi_window: ^0.0.2
  path_provider: ^2.0.11
  list_ext: ^1.0.4
  bitsdojo_window: ^0.1.2
  dart_vlc: ^0.3.0
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - 'assets/cdg/'
